function comp_plot(XMatrix1, YMatrix1, DMatrix1,ylab,titl)
%CREATEFIGURE(XMatrix1, YMatrix1, DMatrix1)
%  XMATRIX1:  errorbar x matrix data
%  YMATRIX1:  errorbar y matrix data
%  DMATRIX1:  errorbar delta matrix data

%  Auto-generated by MATLAB on 27-Jan-2021 13:38:14

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(XMatrix1,YMatrix1,DMatrix1,'LineWidth',6);
set(errorbar1(1),'DisplayName','RML-C','Color',[0 0.800000011920929 0.200000002980232]);
set(errorbar1(2),'DisplayName','RML','Color',[0 0.447058826684952 0.74117648601532]);

% Create ylabel
ylabel(ylab,'FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('Reward','FontWeight','bold','FontSize',20);

% Create title
title(titl);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.7 2.3]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',20,'FontWeight','bold','XTick',[1 2 3],'XTickLabel',...
    {'r','R'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[1 1 1]);

